version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./backend:/app
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: dev_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "55432:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: dev_redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
